[Task] Build html layout
st-tiendinh/FE-Internship-2023_Tien-Dinh-N_FE-Exercise pull request #11
Opened 2023-08-04 09:11 UTC by st-tiendinh

### Description
- Build HTML layout base on Figma design

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-05 03:55 UTC, st-quangnguyen2 commented on index.html
> +</head>
sửa cái `title` ở đây thành tên của trang luôn em

2023-08-05 03:57 UTC, st-quangnguyen2 commented on index.html
> +        <li class="nav-item"><a href="#kids">Kids</a></li>
ở chỗ mấy cái thẻ `a` em thêm cho nó cái `class`, `nav-link` chẳng hạn

2023-08-05 04:02 UTC, st-quangnguyen2 commented on index.html
> +    </ul>
ở đây tại sao em lại tách ra 3 cái `ul li` vậy.
3 thằng này là là một `list` nên mình chỉ cần `ul > li*3` là được.
class name thì ổn rồi, nhưng mà với một list thì cấu anh thường dùng nó ntn
`list > item > object`
ở trường hợp này sẽ là `service-list > service-item > service`

2023-08-05 04:02 UTC, st-quangnguyen2 commented on index.html
> +    </div>
cái này là một `list`

2023-08-05 04:04 UTC, st-quangnguyen2 commented on index.html
> +        </a>
thêm class cho `a`

2023-08-05 04:05 UTC, st-quangnguyen2 commented on index.html
> +            <div class="product-prices">
dùng `h4` cho `product-name`

2023-08-05 04:06 UTC, st-quangnguyen2 commented on index.html
> +        <h3 class="service-detail-title">Free Shipping</h3>
dùng `h4` cho `name`, `title` của `item`

2023-08-05 04:09 UTC, st-quangnguyen2 commented on index.html
> +        </div>
với những chỗ hiển thị một đoạn `content` thì mình dùng thẻ `p` nhé.
với thẻ `div` mục đích sử dụng của nó sẽ là bọc để chia `layout` không dùng chứa `content`

2023-08-05 04:11 UTC, st-quangnguyen2 commented on index.html
> +
phần này nó cũng là một `section`, em dùng thẻ và tên `class` tương tự những `section` khác

2023-08-05 04:12 UTC, st-quangnguyen2 requested changes
@st-tiendinh check cmts

2023-08-05 09:55 UTC, st-quangnguyen2 commented on index.html
> +      <span class="brand-name">E-Shop</span>
ở bài tập này mình sẽ dùng thẻ `h1` bọc cái `logo` của trang

2023-08-05 09:55 UTC, st-quangnguyen2 commented on index.html
> +    <div class="banner-link-wrapper">
`h1` được dùng cho logo rồi nên ở đây em dùng thẻ khác thay thế

2023-08-05 09:56 UTC, st-quangnguyen2 commented on index.html
> +      </li>
`h3` -> `h4`

2023-08-05 10:23 UTC, st-quangnguyen2 commented on index.html
> +      <span class="brand-name">E-Shop</span>
đổi tên tất cả các file ảnh giúp anh
tên file cần rõ ràng, tường minh và đúng fomat

2023-08-05 10:38 UTC, st-tiendinh commented on index.html
> +      <span class="brand-name">E-Shop</span>
ví dụ các ảnh trong product section, em nên đặt là product_1.png, product_2.png được không anh. Trong doc trên github không có ghi chuẩn format đặt file nên em thắc mắc ạ.

2023-08-05 14:20 UTC, st-quangnguyen2 commented on html exercise/index.html
> +<html lang="en">
tên `folder` đang sai `htm-...`

2023-08-05 14:46 UTC, st-tiendinh commented on html exercise/index.html
> +<html lang="en">
dạ anh

2023-08-06 08:53 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      </svg>
không nhúng trực tiếp SVG vao đây nha @st-tiendinh 
bỏ hết những chỗ tương tự

2023-08-06 08:54 UTC, st-quangnguyen2 requested changes
@st-tiendinh check cmt

2023-08-06 08:57 UTC, st-tiendinh commented on html-exercise/index.html
> +      </svg>
vậy các logo và icon mình để rỗng hả anh @st-quangnguyen2

2023-08-06 09:35 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      </svg>
yep, em để lại `i` rồi bỏ class như bình thường

2023-08-07 09:20 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      <h2 class="banner-title">Sale of the <span>summer</span> collection</h2>
`banner` -> `title`

2023-08-07 09:37 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      <ul class="banner-service-list">
bỏ `banner-`

2023-08-07 12:16 UTC, st-manhle requested changes

2023-08-07 12:16 UTC, st-manhle commented on html-exercise/index.html
> +          <img src="./assets/images/shop-logo.svg" alt="E-Shop logo" class="shop-logo-img">
alt của logo = title của trang web e nha

2023-08-08 04:34 UTC, st-quangnguyen2 approved these changes

2023-08-08 04:35 UTC, merged