Task/20230808/st tiendinh styling e shop page
st-tiendinh/FE-Internship-2023_Tien-Dinh-N_FE-Exercise pull request #14
Opened 2023-08-08 10:05 UTC by st-tiendinh

### References
> Layout [Figman design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?type=design&node-id=8-194&mode=design&t=iWa6C0UakTcZPu90-0)

### Description
> Styling E-Shop page

### Screenshot

### Checklist

- [] App run correctly
- [] The code has been tested in the local environment.

2023-08-08 14:55 UTC, st-quangnguyen2 commented on html-exercise/assets/styles/layout.css
> +}
cái này nó cũng ko nằm trong `layout`

2023-08-08 14:58 UTC, st-quangnguyen2 commented on html-exercise/assets/styles/main.css
> +}
`selector` chưa đủ cụ thể

2023-08-08 14:59 UTC, st-quangnguyen2 commented on html-exercise/assets/styles/main.css
> +
`selector` chưa đủ cụ thể

2023-08-09 10:27 UTC, st-manhle requested changes

2023-08-09 10:27 UTC, st-manhle commented on html-exercise/assets/styles/main.css
> +}
highlight của cái gì đây e

2023-08-09 12:07 UTC, st-tiendinh commented on html-exercise/assets/styles/main.css
> +}
@st-manhle Em dùng class này để highlight các đoạn text nhỏ đó anh

2023-08-10 02:30 UTC, st-quangnguyen2 approved these changes

2023-08-10 02:30 UTC, merged